from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision: str = '9ae89b21febe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    op.create_table('attribute_definition', sa.Column('id', sa.UUID(), nullable=False), sa.Column('name', sa.String(length=100), nullable=False), sa.Column('code', sa.String(length=100), nullable=False), sa.Column('description', sa.Text(), nullable=True), sa.Column('data_type', sa.String(length=20), nullable=False), sa.Column('is_required', sa.Boolean(), server_default=sa.text('false'), nullable=False), sa.Column('default_value', sa.Text(), nullable=True), sa.Column('validation_regex', sa.Text(), nullable=True), sa.Column('min_value', sa.Numeric(), nullable=True), sa.Column('max_value', sa.Numeric(), nullable=True), sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True), sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_attribute_definition_code'), 'attribute_definition', ['code'], unique=True)
    op.create_index(op.f('ix_attribute_definition_data_type'), 'attribute_definition', ['data_type'], unique=False)
    op.create_index(op.f('ix_attribute_definition_display_order'), 'attribute_definition', ['display_order'], unique=False)
    op.create_table('color', sa.Column('id', sa.UUID(), nullable=False), sa.Column('name', sa.String(length=50), nullable=False), sa.Column('hex_code', sa.String(length=7), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_color_name'), 'color', ['name'], unique=True)
    op.create_table('construction_type', sa.Column('id', sa.UUID(), nullable=False), sa.Column('name', sa.String(length=100), nullable=False), sa.Column('description', sa.Text(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_construction_type_name'), 'construction_type', ['name'], unique=True)
    op.create_table('country', sa.Column('id', sa.UUID(), nullable=False), sa.Column('name', sa.String(length=100), nullable=False), sa.Column('iso_alpha_2', sa.String(length=2), nullable=False), sa.Column('iso_alpha_3', sa.String(length=3), nullable=False), sa.Column('iso_numeric', sa.String(length=3), nullable=True), sa.Column('region', sa.String(length=50), nullable=True), sa.Column('subregion', sa.String(length=50), nullable=True), sa.Column('currency', sa.String(length=3), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('iso_numeric'))
    op.create_index(op.f('ix_country_iso_alpha_2'), 'country', ['iso_alpha_2'], unique=True)
    op.create_index(op.f('ix_country_iso_alpha_3'), 'country', ['iso_alpha_3'], unique=True)
    op.create_index(op.f('ix_country_name'), 'country', ['name'], unique=False)
    op.create_table('fitment', sa.Column('id', sa.UUID(), nullable=False), sa.Column('year', sa.Integer(), nullable=False), sa.Column('make', sa.String(length=100), nullable=False), sa.Column('model', sa.String(length=100), nullable=False), sa.Column('engine', sa.String(length=100), nullable=True), sa.Column('transmission', sa.String(length=100), nullable=True), sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_fitment_engine'), 'fitment', ['engine'], unique=False)
    op.create_index(op.f('ix_fitment_make'), 'fitment', ['make'], unique=False)
    op.create_index(op.f('ix_fitment_model'), 'fitment', ['model'], unique=False)
    op.create_index(op.f('ix_fitment_transmission'), 'fitment', ['transmission'], unique=False)
    op.create_index(op.f('ix_fitment_year'), 'fitment', ['year'], unique=False)
    op.create_table('hardware_item', sa.Column('id', sa.UUID(), nullable=False), sa.Column('name', sa.String(length=255), nullable=False), sa.Column('description', sa.Text(), nullable=True), sa.Column('part_number', sa.String(length=100), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_hardware_item_name'), 'hardware_item', ['name'], unique=True)
    op.create_index(op.f('ix_hardware_item_part_number'), 'hardware_item', ['part_number'], unique=False)
    op.create_table('packaging_type', sa.Column('id', sa.UUID(), nullable=False), sa.Column('pies_code', sa.String(length=50), nullable=True), sa.Column('name', sa.String(length=100), nullable=False), sa.Column('description', sa.Text(), nullable=True), sa.Column('source', sa.String(length=20), server_default=sa.text("'Custom'"), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_packaging_type_name'), 'packaging_type', ['name'], unique=True)
    op.create_index(op.f('ix_packaging_type_pies_code'), 'packaging_type', ['pies_code'], unique=False)
    op.create_table('price_type', sa.Column('id', sa.UUID(), nullable=False), sa.Column('name', sa.String(length=50), nullable=False), sa.Column('description', sa.Text(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_price_type_name'), 'price_type', ['name'], unique=True)
    op.create_table('product', sa.Column('id', sa.UUID(), nullable=False), sa.Column('part_number', sa.String(length=50), nullable=False), sa.Column('part_number_stripped', sa.String(length=50), nullable=False), sa.Column('application', sa.Text(), nullable=True), sa.Column('vintage', sa.Boolean(), server_default=sa.text('false'), nullable=False), sa.Column('late_model', sa.Boolean(), server_default=sa.text('false'), nullable=False), sa.Column('soft', sa.Boolean(), server_default=sa.text('false'), nullable=False), sa.Column('universal', sa.Boolean(), server_default=sa.text('false'), nullable=False), sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True), sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_product_part_number'), 'product', ['part_number'], unique=True)
    op.create_index(op.f('ix_product_part_number_stripped'), 'product', ['part_number_stripped'], unique=False)
    op.create_table('prop65_chemical', sa.Column('id', sa.UUID(), nullable=False), sa.Column('name', sa.String(length=255), nullable=False), sa.Column('cas_number', sa.String(length=20), nullable=False), sa.Column('type', sa.Enum('CARCINOGEN', 'REPRODUCTIVE_TOXICANT', 'BOTH', name='chemicaltype'), nullable=False), sa.Column('exposure_limit', sa.Numeric(precision=18, scale=9), nullable=True), sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_prop65_chemical_cas_number'), 'prop65_chemical', ['cas_number'], unique=True)
    op.create_index(op.f('ix_prop65_chemical_name'), 'prop65_chemical', ['name'], unique=False)
    op.create_index(op.f('ix_prop65_chemical_type'), 'prop65_chemical', ['type'], unique=False)
    op.create_table('texture', sa.Column('id', sa.UUID(), nullable=False), sa.Column('name', sa.String(length=100), nullable=False), sa.Column('description', sa.Text(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_texture_name'), 'texture', ['name'], unique=True)
    op.create_table('unspsc_code', sa.Column('id', sa.UUID(), nullable=False), sa.Column('code', sa.String(length=10), nullable=False), sa.Column('description', sa.Text(), nullable=False), sa.Column('segment', sa.String(length=255), nullable=True), sa.Column('family', sa.String(length=255), nullable=True), sa.Column('class', sa.String(length=255), nullable=True), sa.Column('commodity', sa.String(length=255), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_unspsc_code_code'), 'unspsc_code', ['code'], unique=True)
    op.create_table('address', sa.Column('id', sa.UUID(), nullable=False), sa.Column('street', sa.String(length=255), nullable=False), sa.Column('city', sa.String(length=100), nullable=False), sa.Column('state', sa.String(length=100), nullable=True), sa.Column('postal_code', sa.String(length=20), nullable=False), sa.Column('country_id', sa.UUID(), nullable=False), sa.Column('latitude', sa.Float(precision=10, decimal_return_scale=7), nullable=True), sa.Column('longitude', sa.Float(precision=10, decimal_return_scale=7), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['country_id'], ['country.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_address_country_id'), 'address', ['country_id'], unique=False)
    op.create_index(op.f('ix_address_postal_code'), 'address', ['postal_code'], unique=False)
    op.create_table('hazardous_material', sa.Column('id', sa.UUID(), nullable=False), sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('un_number', sa.String(length=18), nullable=True), sa.Column('hazard_class', sa.String(length=50), nullable=True), sa.Column('packing_group', sa.String(length=10), nullable=True), sa.Column('handling_instructions', sa.Text(), nullable=True), sa.Column('restricted_transport', sa.Enum('NONE', 'AIR', 'GROUND', 'SEA', 'ALL', name='transportrestriction'), server_default='NONE', nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['product_id'], ['product.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_hazardous_material_hazard_class'), 'hazardous_material', ['hazard_class'], unique=False)
    op.create_index(op.f('ix_hazardous_material_product_id'), 'hazardous_material', ['product_id'], unique=False)
    op.create_index(op.f('ix_hazardous_material_un_number'), 'hazardous_material', ['un_number'], unique=False)
    op.create_table('product_attribute', sa.Column('id', sa.UUID(), nullable=False), sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('attribute_id', sa.UUID(), nullable=False), sa.Column('value_string', sa.Text(), nullable=True), sa.Column('value_number', sa.Numeric(), nullable=True), sa.Column('value_boolean', sa.Boolean(), nullable=True), sa.Column('value_date', sa.DateTime(timezone=True), nullable=True), sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['attribute_id'], ['attribute_definition.id']), sa.ForeignKeyConstraint(['product_id'], ['product.id']), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('product_id', 'attribute_id', name='uix_product_attribute'))
    op.create_index(op.f('ix_product_attribute_attribute_id'), 'product_attribute', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_product_attribute_product_id'), 'product_attribute', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_attribute_value_boolean'), 'product_attribute', ['value_boolean'], unique=False)
    op.create_index(op.f('ix_product_attribute_value_date'), 'product_attribute', ['value_date'], unique=False)
    op.create_index(op.f('ix_product_attribute_value_number'), 'product_attribute', ['value_number'], unique=False)
    op.create_index(op.f('ix_product_attribute_value_string'), 'product_attribute', ['value_string'], unique=False)
    op.create_table('product_chemical', sa.Column('id', sa.UUID(), nullable=False), sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('chemical_id', sa.UUID(), nullable=False), sa.Column('exposure_scenario', sa.Enum('CONSUMER', 'OCCUPATIONAL', 'ENVIRONMENTAL', name='exposurescenario'), nullable=False), sa.Column('warning_required', sa.Boolean(), server_default=sa.text('false'), nullable=False), sa.Column('warning_label', sa.Text(), nullable=True), sa.ForeignKeyConstraint(['chemical_id'], ['prop65_chemical.id']), sa.ForeignKeyConstraint(['product_id'], ['product.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_product_chemical_chemical_id'), 'product_chemical', ['chemical_id'], unique=False)
    op.create_index(op.f('ix_product_chemical_product_id'), 'product_chemical', ['product_id'], unique=False)
    op.create_table('product_color', sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('color_id', sa.UUID(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['color_id'], ['color.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('product_id', 'color_id'))
    op.create_table('product_construction_type', sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('construction_type_id', sa.UUID(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['construction_type_id'], ['construction_type.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('product_id', 'construction_type_id'))
    op.create_table('product_description', sa.Column('id', sa.UUID(), nullable=False), sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('description_type', sa.String(length=20), nullable=False), sa.Column('description', sa.Text(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['product_id'], ['product.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_product_description_description_type'), 'product_description', ['description_type'], unique=False)
    op.create_table('product_fitment', sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('fitment_id', sa.UUID(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['fitment_id'], ['fitment.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('product_id', 'fitment_id'))
    op.create_table('product_hardware', sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('hardware_id', sa.UUID(), nullable=False), sa.Column('quantity', sa.Integer(), nullable=False), sa.Column('is_optional', sa.Integer(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['hardware_id'], ['hardware_item.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('product_id', 'hardware_id'), sa.UniqueConstraint('product_id', 'hardware_id', name='uix_product_hardware'))
    op.create_table('product_marketing', sa.Column('id', sa.UUID(), nullable=False), sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('marketing_type', sa.String(length=20), nullable=False), sa.Column('content', sa.Text(), nullable=False), sa.Column('position', sa.Integer(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['product_id'], ['product.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_product_marketing_position'), 'product_marketing', ['position'], unique=False)
    op.create_table('product_packaging', sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('packaging_type_id', sa.UUID(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['packaging_type_id'], ['packaging_type.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('product_id', 'packaging_type_id'))
    op.create_table('product_supersession', sa.Column('id', sa.UUID(), nullable=False), sa.Column('old_product_id', sa.UUID(), nullable=False), sa.Column('new_product_id', sa.UUID(), nullable=False), sa.Column('reason', sa.Text(), nullable=True), sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['new_product_id'], ['product.id']), sa.ForeignKeyConstraint(['old_product_id'], ['product.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_product_supersession_changed_at'), 'product_supersession', ['changed_at'], unique=False)
    op.create_index(op.f('ix_product_supersession_new_product_id'), 'product_supersession', ['new_product_id'], unique=False)
    op.create_index(op.f('ix_product_supersession_old_product_id'), 'product_supersession', ['old_product_id'], unique=False)
    op.create_table('product_texture', sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('texture_id', sa.UUID(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['texture_id'], ['texture.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('product_id', 'texture_id'))
    op.create_table('product_unspsc', sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('unspsc_code_id', sa.UUID(), nullable=False), sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['unspsc_code_id'], ['unspsc_code.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('product_id', 'unspsc_code_id'))
    op.create_table('tariff_code', sa.Column('id', sa.UUID(), nullable=False), sa.Column('code', sa.String(length=15), nullable=False), sa.Column('description', sa.Text(), nullable=False), sa.Column('country_id', sa.UUID(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['country_id'], ['country.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_tariff_code_code'), 'tariff_code', ['code'], unique=False)
    op.create_index(op.f('ix_tariff_code_country_id'), 'tariff_code', ['country_id'], unique=False)
    op.create_table('warning', sa.Column('id', sa.UUID(), nullable=False), sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('chemical_id', sa.UUID(), nullable=False), sa.Column('warning_text', sa.Text(), nullable=False), sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['chemical_id'], ['prop65_chemical.id']), sa.ForeignKeyConstraint(['product_id'], ['product.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_warning_chemical_id'), 'warning', ['chemical_id'], unique=False)
    op.create_index(op.f('ix_warning_product_id'), 'warning', ['product_id'], unique=False)
    op.create_table('company', sa.Column('id', sa.UUID(), nullable=False), sa.Column('name', sa.String(length=255), nullable=False), sa.Column('headquarters_address_id', sa.UUID(), nullable=True), sa.Column('billing_address_id', sa.UUID(), nullable=True), sa.Column('shipping_address_id', sa.UUID(), nullable=True), sa.Column('account_number', sa.String(length=50), nullable=True), sa.Column('account_type', sa.String(length=50), nullable=False), sa.Column('industry', sa.String(length=100), nullable=True), sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['billing_address_id'], ['address.id']), sa.ForeignKeyConstraint(['headquarters_address_id'], ['address.id']), sa.ForeignKeyConstraint(['shipping_address_id'], ['address.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_company_account_number'), 'company', ['account_number'], unique=True)
    op.create_table('product_tariff_code', sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('tariff_code_id', sa.UUID(), nullable=False), sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['tariff_code_id'], ['tariff_code.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('product_id', 'tariff_code_id'))
    op.create_table('warehouse', sa.Column('id', sa.UUID(), nullable=False), sa.Column('name', sa.String(length=255), nullable=False), sa.Column('address_id', sa.UUID(), nullable=True), sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['address_id'], ['address.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_warehouse_is_active'), 'warehouse', ['is_active'], unique=False)
    op.create_index(op.f('ix_warehouse_name'), 'warehouse', ['name'], unique=False)
    op.create_table('brand', sa.Column('id', sa.UUID(), nullable=False), sa.Column('name', sa.String(length=100), nullable=False), sa.Column('parent_company_id', sa.UUID(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['parent_company_id'], ['company.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_brand_name'), 'brand', ['name'], unique=False)
    op.create_table('manufacturer', sa.Column('id', sa.UUID(), nullable=False), sa.Column('name', sa.String(length=255), nullable=False), sa.Column('company_id', sa.UUID(), nullable=True), sa.Column('address_id', sa.UUID(), nullable=True), sa.Column('billing_address_id', sa.UUID(), nullable=True), sa.Column('shipping_address_id', sa.UUID(), nullable=True), sa.Column('country_id', sa.UUID(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['address_id'], ['address.id']), sa.ForeignKeyConstraint(['billing_address_id'], ['address.id']), sa.ForeignKeyConstraint(['company_id'], ['company.id']), sa.ForeignKeyConstraint(['country_id'], ['country.id']), sa.ForeignKeyConstraint(['shipping_address_id'], ['address.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_manufacturer_company_id'), 'manufacturer', ['company_id'], unique=False)
    op.create_index(op.f('ix_manufacturer_country_id'), 'manufacturer', ['country_id'], unique=False)
    op.create_index(op.f('ix_manufacturer_name'), 'manufacturer', ['name'], unique=False)
    op.create_table('product_stock', sa.Column('id', sa.UUID(), nullable=False), sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('warehouse_id', sa.UUID(), nullable=False), sa.Column('quantity', sa.Integer(), server_default=sa.text('0'), nullable=False), sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['product_id'], ['product.id']), sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_product_stock_product_id'), 'product_stock', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_stock_quantity'), 'product_stock', ['quantity'], unique=False)
    op.create_index(op.f('ix_product_stock_warehouse_id'), 'product_stock', ['warehouse_id'], unique=False)
    op.create_table('user', sa.Column('id', sa.UUID(), nullable=False), sa.Column('email', sa.String(length=255), nullable=False), sa.Column('hashed_password', sa.String(length=255), nullable=False), sa.Column('full_name', sa.String(length=255), nullable=False), sa.Column('role', sa.Enum('admin', 'manager', 'client', 'distributor', 'read_only', name='userrole'), nullable=False), sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False), sa.Column('company_id', sa.UUID(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['company_id'], ['company.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('media', sa.Column('id', sa.UUID(), nullable=False), sa.Column('filename', sa.String(length=255), nullable=False), sa.Column('file_path', sa.String(length=512), nullable=False), sa.Column('file_size', sa.Integer(), nullable=False), sa.Column('media_type', sa.Enum('IMAGE', 'DOCUMENT', 'VIDEO', 'MSDS', 'DOT_APPROVAL', 'OTHER', name='mediatype'), nullable=False), sa.Column('mime_type', sa.String(length=127), nullable=False), sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', 'RESTRICTED', name='mediavisibility'), nullable=False), sa.Column('file_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False), sa.Column('uploaded_by_id', sa.UUID(), nullable=False), sa.Column('is_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False), sa.Column('approved_by_id', sa.UUID(), nullable=True), sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['approved_by_id'], ['user.id']), sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id']), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('file_path'))
    op.create_table('product_activity', sa.Column('id', sa.UUID(), nullable=False), sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('status', sa.String(length=20), nullable=False), sa.Column('reason', sa.Text(), nullable=True), sa.Column('changed_by_id', sa.UUID(), nullable=True), sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['changed_by_id'], ['user.id']), sa.ForeignKeyConstraint(['product_id'], ['product.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_product_activity_changed_at'), 'product_activity', ['changed_at'], unique=False)
    op.create_index(op.f('ix_product_activity_status'), 'product_activity', ['status'], unique=False)
    op.create_table('product_brand_history', sa.Column('id', sa.UUID(), nullable=False), sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('old_brand_id', sa.UUID(), nullable=True), sa.Column('new_brand_id', sa.UUID(), nullable=False), sa.Column('changed_by_id', sa.UUID(), nullable=True), sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['changed_by_id'], ['user.id']), sa.ForeignKeyConstraint(['new_brand_id'], ['brand.id']), sa.ForeignKeyConstraint(['old_brand_id'], ['brand.id']), sa.ForeignKeyConstraint(['product_id'], ['product.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_product_brand_history_changed_at'), 'product_brand_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_product_brand_history_product_id'), 'product_brand_history', ['product_id'], unique=False)
    op.create_table('product_country_origin', sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('country_id', sa.UUID(), nullable=False), sa.Column('manufacturer_id', sa.UUID(), nullable=True), sa.Column('origin_type', sa.Integer(), nullable=False), sa.Column('origin_order', sa.Integer(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ondelete='SET NULL'), sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('product_id', 'country_id'), sa.UniqueConstraint('product_id', 'country_id', name='uix_product_country'))
    op.create_table('product_dot_approval', sa.Column('id', sa.UUID(), nullable=False), sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('approval_status', sa.Enum('APPROVED', 'PENDING', 'REVOKED', 'NOT_REQUIRED', name='approvalstatus'), nullable=False), sa.Column('approval_number', sa.String(length=100), nullable=True), sa.Column('approved_by', sa.String(length=255), nullable=True), sa.Column('approval_date', sa.Date(), nullable=True), sa.Column('expiration_date', sa.Date(), nullable=True), sa.Column('reason', sa.Text(), nullable=True), sa.Column('changed_by_id', sa.UUID(), nullable=True), sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['changed_by_id'], ['user.id']), sa.ForeignKeyConstraint(['product_id'], ['product.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_product_dot_approval_approval_number'), 'product_dot_approval', ['approval_number'], unique=False)
    op.create_index(op.f('ix_product_dot_approval_approval_status'), 'product_dot_approval', ['approval_status'], unique=False)
    op.create_index(op.f('ix_product_dot_approval_product_id'), 'product_dot_approval', ['product_id'], unique=False)
    op.create_table('product_interchange', sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('interchange_number', sa.Integer(), nullable=False), sa.Column('brand_id', sa.UUID(), nullable=True), sa.Column('notes', sa.Integer(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ondelete='SET NULL'), sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('product_id'), sa.UniqueConstraint('product_id', 'interchange_number', 'brand_id', name='uix_product_interchange'))
    op.create_table('product_measurement', sa.Column('id', sa.UUID(), nullable=False), sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('manufacturer_id', sa.UUID(), nullable=True), sa.Column('length', sa.Numeric(precision=10, scale=3), nullable=True), sa.Column('width', sa.Numeric(precision=10, scale=3), nullable=True), sa.Column('height', sa.Numeric(precision=10, scale=3), nullable=True), sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=True), sa.Column('volume', sa.Numeric(precision=10, scale=3), nullable=True), sa.Column('dimensional_weight', sa.Numeric(precision=10, scale=3), nullable=True), sa.Column('effective_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id']), sa.ForeignKeyConstraint(['product_id'], ['product.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_product_measurement_effective_date'), 'product_measurement', ['effective_date'], unique=False)
    op.create_index(op.f('ix_product_measurement_manufacturer_id'), 'product_measurement', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_product_measurement_product_id'), 'product_measurement', ['product_id'], unique=False)
    op.create_table('product_pricing', sa.Column('id', sa.UUID(), nullable=False), sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('pricing_type_id', sa.UUID(), nullable=False), sa.Column('manufacturer_id', sa.UUID(), nullable=True), sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False), sa.Column('currency', sa.String(length=3), server_default=sa.text("'USD'"), nullable=False), sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id']), sa.ForeignKeyConstraint(['pricing_type_id'], ['price_type.id']), sa.ForeignKeyConstraint(['product_id'], ['product.id']), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_product_pricing_manufacturer_id'), 'product_pricing', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_product_pricing_pricing_type_id'), 'product_pricing', ['pricing_type_id'], unique=False)
    op.create_index(op.f('ix_product_pricing_product_id'), 'product_pricing', ['product_id'], unique=False)
    op.create_table('product_media', sa.Column('product_id', sa.UUID(), nullable=False), sa.Column('media_id', sa.UUID(), nullable=False), sa.Column('display_order', sa.Integer(), nullable=False), sa.Column('is_primary', sa.Integer(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('product_id', 'media_id'))
def downgrade() -> None:
    op.drop_table('product_media')
    op.drop_index(op.f('ix_product_pricing_product_id'), table_name='product_pricing')
    op.drop_index(op.f('ix_product_pricing_pricing_type_id'), table_name='product_pricing')
    op.drop_index(op.f('ix_product_pricing_manufacturer_id'), table_name='product_pricing')
    op.drop_table('product_pricing')
    op.drop_index(op.f('ix_product_measurement_product_id'), table_name='product_measurement')
    op.drop_index(op.f('ix_product_measurement_manufacturer_id'), table_name='product_measurement')
    op.drop_index(op.f('ix_product_measurement_effective_date'), table_name='product_measurement')
    op.drop_table('product_measurement')
    op.drop_table('product_interchange')
    op.drop_index(op.f('ix_product_dot_approval_product_id'), table_name='product_dot_approval')
    op.drop_index(op.f('ix_product_dot_approval_approval_status'), table_name='product_dot_approval')
    op.drop_index(op.f('ix_product_dot_approval_approval_number'), table_name='product_dot_approval')
    op.drop_table('product_dot_approval')
    op.drop_table('product_country_origin')
    op.drop_index(op.f('ix_product_brand_history_product_id'), table_name='product_brand_history')
    op.drop_index(op.f('ix_product_brand_history_changed_at'), table_name='product_brand_history')
    op.drop_table('product_brand_history')
    op.drop_index(op.f('ix_product_activity_status'), table_name='product_activity')
    op.drop_index(op.f('ix_product_activity_changed_at'), table_name='product_activity')
    op.drop_table('product_activity')
    op.drop_table('media')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_product_stock_warehouse_id'), table_name='product_stock')
    op.drop_index(op.f('ix_product_stock_quantity'), table_name='product_stock')
    op.drop_index(op.f('ix_product_stock_product_id'), table_name='product_stock')
    op.drop_table('product_stock')
    op.drop_index(op.f('ix_manufacturer_name'), table_name='manufacturer')
    op.drop_index(op.f('ix_manufacturer_country_id'), table_name='manufacturer')
    op.drop_index(op.f('ix_manufacturer_company_id'), table_name='manufacturer')
    op.drop_table('manufacturer')
    op.drop_index(op.f('ix_brand_name'), table_name='brand')
    op.drop_table('brand')
    op.drop_index(op.f('ix_warehouse_name'), table_name='warehouse')
    op.drop_index(op.f('ix_warehouse_is_active'), table_name='warehouse')
    op.drop_table('warehouse')
    op.drop_table('product_tariff_code')
    op.drop_index(op.f('ix_company_account_number'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_warning_product_id'), table_name='warning')
    op.drop_index(op.f('ix_warning_chemical_id'), table_name='warning')
    op.drop_table('warning')
    op.drop_index(op.f('ix_tariff_code_country_id'), table_name='tariff_code')
    op.drop_index(op.f('ix_tariff_code_code'), table_name='tariff_code')
    op.drop_table('tariff_code')
    op.drop_table('product_unspsc')
    op.drop_table('product_texture')
    op.drop_index(op.f('ix_product_supersession_old_product_id'), table_name='product_supersession')
    op.drop_index(op.f('ix_product_supersession_new_product_id'), table_name='product_supersession')
    op.drop_index(op.f('ix_product_supersession_changed_at'), table_name='product_supersession')
    op.drop_table('product_supersession')
    op.drop_table('product_packaging')
    op.drop_index(op.f('ix_product_marketing_position'), table_name='product_marketing')
    op.drop_table('product_marketing')
    op.drop_table('product_hardware')
    op.drop_table('product_fitment')
    op.drop_index(op.f('ix_product_description_description_type'), table_name='product_description')
    op.drop_table('product_description')
    op.drop_table('product_construction_type')
    op.drop_table('product_color')
    op.drop_index(op.f('ix_product_chemical_product_id'), table_name='product_chemical')
    op.drop_index(op.f('ix_product_chemical_chemical_id'), table_name='product_chemical')
    op.drop_table('product_chemical')
    op.drop_index(op.f('ix_product_attribute_value_string'), table_name='product_attribute')
    op.drop_index(op.f('ix_product_attribute_value_number'), table_name='product_attribute')
    op.drop_index(op.f('ix_product_attribute_value_date'), table_name='product_attribute')
    op.drop_index(op.f('ix_product_attribute_value_boolean'), table_name='product_attribute')
    op.drop_index(op.f('ix_product_attribute_product_id'), table_name='product_attribute')
    op.drop_index(op.f('ix_product_attribute_attribute_id'), table_name='product_attribute')
    op.drop_table('product_attribute')
    op.drop_index(op.f('ix_hazardous_material_un_number'), table_name='hazardous_material')
    op.drop_index(op.f('ix_hazardous_material_product_id'), table_name='hazardous_material')
    op.drop_index(op.f('ix_hazardous_material_hazard_class'), table_name='hazardous_material')
    op.drop_table('hazardous_material')
    op.drop_index(op.f('ix_address_postal_code'), table_name='address')
    op.drop_index(op.f('ix_address_country_id'), table_name='address')
    op.drop_table('address')
    op.drop_index(op.f('ix_unspsc_code_code'), table_name='unspsc_code')
    op.drop_table('unspsc_code')
    op.drop_index(op.f('ix_texture_name'), table_name='texture')
    op.drop_table('texture')
    op.drop_index(op.f('ix_prop65_chemical_type'), table_name='prop65_chemical')
    op.drop_index(op.f('ix_prop65_chemical_name'), table_name='prop65_chemical')
    op.drop_index(op.f('ix_prop65_chemical_cas_number'), table_name='prop65_chemical')
    op.drop_table('prop65_chemical')
    op.drop_index(op.f('ix_product_part_number_stripped'), table_name='product')
    op.drop_index(op.f('ix_product_part_number'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_price_type_name'), table_name='price_type')
    op.drop_table('price_type')
    op.drop_index(op.f('ix_packaging_type_pies_code'), table_name='packaging_type')
    op.drop_index(op.f('ix_packaging_type_name'), table_name='packaging_type')
    op.drop_table('packaging_type')
    op.drop_index(op.f('ix_hardware_item_part_number'), table_name='hardware_item')
    op.drop_index(op.f('ix_hardware_item_name'), table_name='hardware_item')
    op.drop_table('hardware_item')
    op.drop_index(op.f('ix_fitment_year'), table_name='fitment')
    op.drop_index(op.f('ix_fitment_transmission'), table_name='fitment')
    op.drop_index(op.f('ix_fitment_model'), table_name='fitment')
    op.drop_index(op.f('ix_fitment_make'), table_name='fitment')
    op.drop_index(op.f('ix_fitment_engine'), table_name='fitment')
    op.drop_table('fitment')
    op.drop_index(op.f('ix_country_name'), table_name='country')
    op.drop_index(op.f('ix_country_iso_alpha_3'), table_name='country')
    op.drop_index(op.f('ix_country_iso_alpha_2'), table_name='country')
    op.drop_table('country')
    op.drop_index(op.f('ix_construction_type_name'), table_name='construction_type')
    op.drop_table('construction_type')
    op.drop_index(op.f('ix_color_name'), table_name='color')
    op.drop_table('color')
    op.drop_index(op.f('ix_attribute_definition_display_order'), table_name='attribute_definition')
    op.drop_index(op.f('ix_attribute_definition_data_type'), table_name='attribute_definition')
    op.drop_index(op.f('ix_attribute_definition_code'), table_name='attribute_definition')
    op.drop_table('attribute_definition')