name: Bug Report
description: File a detailed report to help us fix issues effectively.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill in the details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly describe the issue or unexpected behavior.
      placeholder: Describe the bug you encountered.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the detailed steps required to reproduce this bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Observe the issue
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what should have happened.
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: What happened instead?
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment Information
      description: Include OS, Python version, project version, or relevant information.
      placeholder: e.g., Windows 11, Python 3.11.4, Project Version 1.0.0
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs
      description: Attach screenshots or log outputs if relevant.
      placeholder: Drag and drop screenshots or paste logs here.
    validations:
      required: false
