from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
revision: str = '48a3e13baa8e'
down_revision: Union[str, None] = '0d95e4fb1138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    op.add_column('vehicle_to_bed_config', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_bed_config', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_bed_config', sa.Column('is_deleted', sa.Boolean(), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_bed_config', sa.Column('created_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.add_column('vehicle_to_bed_config', sa.Column('updated_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.create_index(op.f('ix_vcdb_vehicle_to_bed_config_is_deleted'), 'vehicle_to_bed_config', ['is_deleted'], unique=False, schema='vcdb')
    op.add_column('vehicle_to_body_style_config', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_body_style_config', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_body_style_config', sa.Column('is_deleted', sa.Boolean(), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_body_style_config', sa.Column('created_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.add_column('vehicle_to_body_style_config', sa.Column('updated_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.create_index(op.f('ix_vcdb_vehicle_to_body_style_config_is_deleted'), 'vehicle_to_body_style_config', ['is_deleted'], unique=False, schema='vcdb')
    op.add_column('vehicle_to_brake_config', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_brake_config', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_brake_config', sa.Column('is_deleted', sa.Boolean(), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_brake_config', sa.Column('created_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.add_column('vehicle_to_brake_config', sa.Column('updated_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.create_index(op.f('ix_vcdb_vehicle_to_brake_config_is_deleted'), 'vehicle_to_brake_config', ['is_deleted'], unique=False, schema='vcdb')
    op.add_column('vehicle_to_drive_type', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_drive_type', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_drive_type', sa.Column('is_deleted', sa.Boolean(), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_drive_type', sa.Column('created_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.add_column('vehicle_to_drive_type', sa.Column('updated_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.create_index(op.f('ix_vcdb_vehicle_to_drive_type_is_deleted'), 'vehicle_to_drive_type', ['is_deleted'], unique=False, schema='vcdb')
    op.add_column('vehicle_to_engine_config', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_engine_config', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_engine_config', sa.Column('is_deleted', sa.Boolean(), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_engine_config', sa.Column('created_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.add_column('vehicle_to_engine_config', sa.Column('updated_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.create_index(op.f('ix_vcdb_vehicle_to_engine_config_is_deleted'), 'vehicle_to_engine_config', ['is_deleted'], unique=False, schema='vcdb')
    op.add_column('vehicle_to_mfr_body_code', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_mfr_body_code', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_mfr_body_code', sa.Column('is_deleted', sa.Boolean(), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_mfr_body_code', sa.Column('created_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.add_column('vehicle_to_mfr_body_code', sa.Column('updated_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.create_index(op.f('ix_vcdb_vehicle_to_mfr_body_code_is_deleted'), 'vehicle_to_mfr_body_code', ['is_deleted'], unique=False, schema='vcdb')
    op.add_column('vehicle_to_spring_type_config', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_spring_type_config', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_spring_type_config', sa.Column('is_deleted', sa.Boolean(), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_spring_type_config', sa.Column('created_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.add_column('vehicle_to_spring_type_config', sa.Column('updated_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.create_index(op.f('ix_vcdb_vehicle_to_spring_type_config_is_deleted'), 'vehicle_to_spring_type_config', ['is_deleted'], unique=False, schema='vcdb')
    op.add_column('vehicle_to_steering_config', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_steering_config', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_steering_config', sa.Column('is_deleted', sa.Boolean(), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_steering_config', sa.Column('created_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.add_column('vehicle_to_steering_config', sa.Column('updated_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.create_index(op.f('ix_vcdb_vehicle_to_steering_config_is_deleted'), 'vehicle_to_steering_config', ['is_deleted'], unique=False, schema='vcdb')
    op.add_column('vehicle_to_transmission', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_transmission', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_transmission', sa.Column('is_deleted', sa.Boolean(), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_transmission', sa.Column('created_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.add_column('vehicle_to_transmission', sa.Column('updated_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.create_index(op.f('ix_vcdb_vehicle_to_transmission_is_deleted'), 'vehicle_to_transmission', ['is_deleted'], unique=False, schema='vcdb')
    op.add_column('vehicle_to_wheel_base', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_wheel_base', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_wheel_base', sa.Column('is_deleted', sa.Boolean(), nullable=False), schema='vcdb')
    op.add_column('vehicle_to_wheel_base', sa.Column('created_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.add_column('vehicle_to_wheel_base', sa.Column('updated_by_id', sa.UUID(), nullable=True), schema='vcdb')
    op.create_index(op.f('ix_vcdb_vehicle_to_wheel_base_is_deleted'), 'vehicle_to_wheel_base', ['is_deleted'], unique=False, schema='vcdb')
def downgrade() -> None:
    op.drop_index(op.f('ix_vcdb_vehicle_to_wheel_base_is_deleted'), table_name='vehicle_to_wheel_base', schema='vcdb')
    op.drop_column('vehicle_to_wheel_base', 'updated_by_id', schema='vcdb')
    op.drop_column('vehicle_to_wheel_base', 'created_by_id', schema='vcdb')
    op.drop_column('vehicle_to_wheel_base', 'is_deleted', schema='vcdb')
    op.drop_column('vehicle_to_wheel_base', 'updated_at', schema='vcdb')
    op.drop_column('vehicle_to_wheel_base', 'created_at', schema='vcdb')
    op.drop_index(op.f('ix_vcdb_vehicle_to_transmission_is_deleted'), table_name='vehicle_to_transmission', schema='vcdb')
    op.drop_column('vehicle_to_transmission', 'updated_by_id', schema='vcdb')
    op.drop_column('vehicle_to_transmission', 'created_by_id', schema='vcdb')
    op.drop_column('vehicle_to_transmission', 'is_deleted', schema='vcdb')
    op.drop_column('vehicle_to_transmission', 'updated_at', schema='vcdb')
    op.drop_column('vehicle_to_transmission', 'created_at', schema='vcdb')
    op.drop_index(op.f('ix_vcdb_vehicle_to_steering_config_is_deleted'), table_name='vehicle_to_steering_config', schema='vcdb')
    op.drop_column('vehicle_to_steering_config', 'updated_by_id', schema='vcdb')
    op.drop_column('vehicle_to_steering_config', 'created_by_id', schema='vcdb')
    op.drop_column('vehicle_to_steering_config', 'is_deleted', schema='vcdb')
    op.drop_column('vehicle_to_steering_config', 'updated_at', schema='vcdb')
    op.drop_column('vehicle_to_steering_config', 'created_at', schema='vcdb')
    op.drop_index(op.f('ix_vcdb_vehicle_to_spring_type_config_is_deleted'), table_name='vehicle_to_spring_type_config', schema='vcdb')
    op.drop_column('vehicle_to_spring_type_config', 'updated_by_id', schema='vcdb')
    op.drop_column('vehicle_to_spring_type_config', 'created_by_id', schema='vcdb')
    op.drop_column('vehicle_to_spring_type_config', 'is_deleted', schema='vcdb')
    op.drop_column('vehicle_to_spring_type_config', 'updated_at', schema='vcdb')
    op.drop_column('vehicle_to_spring_type_config', 'created_at', schema='vcdb')
    op.drop_index(op.f('ix_vcdb_vehicle_to_mfr_body_code_is_deleted'), table_name='vehicle_to_mfr_body_code', schema='vcdb')
    op.drop_column('vehicle_to_mfr_body_code', 'updated_by_id', schema='vcdb')
    op.drop_column('vehicle_to_mfr_body_code', 'created_by_id', schema='vcdb')
    op.drop_column('vehicle_to_mfr_body_code', 'is_deleted', schema='vcdb')
    op.drop_column('vehicle_to_mfr_body_code', 'updated_at', schema='vcdb')
    op.drop_column('vehicle_to_mfr_body_code', 'created_at', schema='vcdb')
    op.drop_index(op.f('ix_vcdb_vehicle_to_engine_config_is_deleted'), table_name='vehicle_to_engine_config', schema='vcdb')
    op.drop_column('vehicle_to_engine_config', 'updated_by_id', schema='vcdb')
    op.drop_column('vehicle_to_engine_config', 'created_by_id', schema='vcdb')
    op.drop_column('vehicle_to_engine_config', 'is_deleted', schema='vcdb')
    op.drop_column('vehicle_to_engine_config', 'updated_at', schema='vcdb')
    op.drop_column('vehicle_to_engine_config', 'created_at', schema='vcdb')
    op.drop_index(op.f('ix_vcdb_vehicle_to_drive_type_is_deleted'), table_name='vehicle_to_drive_type', schema='vcdb')
    op.drop_column('vehicle_to_drive_type', 'updated_by_id', schema='vcdb')
    op.drop_column('vehicle_to_drive_type', 'created_by_id', schema='vcdb')
    op.drop_column('vehicle_to_drive_type', 'is_deleted', schema='vcdb')
    op.drop_column('vehicle_to_drive_type', 'updated_at', schema='vcdb')
    op.drop_column('vehicle_to_drive_type', 'created_at', schema='vcdb')
    op.drop_index(op.f('ix_vcdb_vehicle_to_brake_config_is_deleted'), table_name='vehicle_to_brake_config', schema='vcdb')
    op.drop_column('vehicle_to_brake_config', 'updated_by_id', schema='vcdb')
    op.drop_column('vehicle_to_brake_config', 'created_by_id', schema='vcdb')
    op.drop_column('vehicle_to_brake_config', 'is_deleted', schema='vcdb')
    op.drop_column('vehicle_to_brake_config', 'updated_at', schema='vcdb')
    op.drop_column('vehicle_to_brake_config', 'created_at', schema='vcdb')
    op.drop_index(op.f('ix_vcdb_vehicle_to_body_style_config_is_deleted'), table_name='vehicle_to_body_style_config', schema='vcdb')
    op.drop_column('vehicle_to_body_style_config', 'updated_by_id', schema='vcdb')
    op.drop_column('vehicle_to_body_style_config', 'created_by_id', schema='vcdb')
    op.drop_column('vehicle_to_body_style_config', 'is_deleted', schema='vcdb')
    op.drop_column('vehicle_to_body_style_config', 'updated_at', schema='vcdb')
    op.drop_column('vehicle_to_body_style_config', 'created_at', schema='vcdb')
    op.drop_index(op.f('ix_vcdb_vehicle_to_bed_config_is_deleted'), table_name='vehicle_to_bed_config', schema='vcdb')
    op.drop_column('vehicle_to_bed_config', 'updated_by_id', schema='vcdb')
    op.drop_column('vehicle_to_bed_config', 'created_by_id', schema='vcdb')
    op.drop_column('vehicle_to_bed_config', 'is_deleted', schema='vcdb')
    op.drop_column('vehicle_to_bed_config', 'updated_at', schema='vcdb')
    op.drop_column('vehicle_to_bed_config', 'created_at', schema='vcdb')