FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy application code
COPY . .

# Run the application
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
