version: '3.8'

services:
  # Server base image build (not directly used as a service)
  server-base:
    build:
      context: ./tests/docker
      dockerfile: server.Dockerfile
    image: crown-test-server:latest
    profiles: ["build"]

  # Server 1 (Database role)
  server1:
    image: crown-test-server:latest
    hostname: server1
    container_name: crown-test-server1
    privileged: true
    networks:
      crown-test-network:
        ipv4_address: 172.28.1.10
    ports:
      - "2201:22"
      - "5432:5432"  # PostgreSQL
    environment:
      - SERVER_ROLE=database
    healthcheck:
      test: ["CMD", "systemctl", "is-system-running"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  # Server 2 (Backend role)
  server2:
    image: crown-test-server:latest
    hostname: server2
    container_name: crown-test-server2
    privileged: true
    networks:
      crown-test-network:
        ipv4_address: 172.28.1.11
    ports:
      - "2202:22"
      - "8000:8000"  # Backend API
    environment:
      - SERVER_ROLE=backend
    healthcheck:
      test: ["CMD", "systemctl", "is-system-running"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  # Server 3 (Frontend role)
  server3:
    image: crown-test-server:latest
    hostname: server3
    container_name: crown-test-server3
    privileged: true
    networks:
      crown-test-network:
        ipv4_address: 172.28.1.12
    ports:
      - "2203:22"
      - "80:80"      # Nginx
    environment:
      - SERVER_ROLE=frontend
    healthcheck:
      test: ["CMD", "systemctl", "is-system-running"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  # Test runner service
  test-runner:
    build:
      context: .
      dockerfile: tests/docker/test_runner.Dockerfile
    container_name: crown-test-runner
    volumes:
      - .:/app
      - test-deployment-volume:/app/test-deployment
      - /var/run/docker.sock:/var/run/docker.sock
      - ./test-output:/test-output
    working_dir: /app
    networks:
      - crown-test-network
    depends_on:
      server1:
        condition: service_healthy
      server2:
        condition: service_healthy
      server3:
        condition: service_healthy
    environment:
      - SERVER1_IP=172.28.1.10
      - SERVER2_IP=172.28.1.11
      - SERVER3_IP=172.28.1.12
      - SSH_USER=crown_test
      - TEST_MODE=true
      - PYTHONPATH=/app
    command: bash /app/tests/docker/test_runner.sh

networks:
  crown-test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/24

volumes:
  test-deployment-volume:
