# File: crown_deploy/docker-compose.enhanced.yml

services:
  # Enhanced base server image
  server-base:
    build:
      context: ./tests/docker
      dockerfile: enhanced-server.Dockerfile
    image: crown-enhanced-server:latest
    privileged: true  # Required for systemd

  # Server 1
  server1:
    image: crown-enhanced-server:latest
    hostname: server1
    container_name: crown-test-server1
    privileged: true
    networks:
      crown-test-network:
        ipv4_address: 172.28.1.10
    ports:
      - "2201:22"
    healthcheck:
      test: [ "CMD", "systemctl", "is-system-running" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  # Server 2
  server2:
    image: crown-enhanced-server:latest
    hostname: server2
    container_name: crown-test-server2
    privileged: true
    networks:
      crown-test-network:
        ipv4_address: 172.28.1.11
    ports:
      - "2202:22"
    healthcheck:
      test: [ "CMD", "systemctl", "is-system-running" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  # Server 3
  server3:
    image: crown-enhanced-server:latest
    hostname: server3
    container_name: crown-test-server3
    privileged: true
    networks:
      crown-test-network:
        ipv4_address: 172.28.1.12
    ports:
      - "2203:22"
    healthcheck:
      test: [ "CMD", "systemctl", "is-system-running" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  # Test runner service
  test-runner:
    build:
      context: .
      dockerfile: tests/docker/TestRunner.Dockerfile
    container_name: crown-test-runner
    volumes:
      - .:/app/crown_deploy
      - test-deployment-volume:/app/test-deployment
      - ./tests/docker/enhanced-test-runner.sh:/test-runner.sh
      - /var/run/docker.sock:/var/run/docker.sock
      - ./test-output:/test-output
    working_dir: /app
    networks:
      - crown-test-network
    depends_on:
      server1:
        condition: service_healthy
      server2:
        condition: service_healthy
      server3:
        condition: service_healthy
    environment:
      - SERVER1_IP=172.28.1.10
      - SERVER2_IP=172.28.1.11
      - SERVER3_IP=172.28.1.12
      - SSH_USER=crown_test
      - TEST_MODE=true
      - PYTHONPATH=/app
      - EXTRACT_SCRIPTS=true
    command: bash /test-runner.sh

networks:
  crown-test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/24

volumes:
  test-deployment-volume:
