name: Process Structure on Push

on:
  push:
    branches:
      - main  # Adjust this if you want to trigger on other branches

permissions:
  contents: write

jobs:
  process_structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Adjust based on your requirement

      - name: Process Everything
        run: |
          rm -rf processed_project
          mkdir -p processed_project
          python backend-stripper.py backend/ --output processed_project/backend_stripped/
          python frontend-stripper.py frontend/ --output processed_project/frontend_stripped/
          python code-structure-mapper2.py backend/ --output processed_project/backend_structure --format directory
          python code-structure-mapper.py backend/ --output processed_project/backend_structure.md --include-docstrings
          python frontend-structure-mapper.py frontend/ --output processed_project/frontend_structure.md
          cat processed_project/backend_structure.md processed_project/frontend_structure.md > processed_project/full_structure.md

      - name: Upload Processed Structure as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed-structure
          path: processed_project/

      - name: Commit and Push Processed Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git fetch origin
          git checkout -B processed-project
          git add -f processed_project/
          git commit -m "Update processed structure [Automated]" || echo "No changes to commit"

          # Push to a separate branch to prevent conflicts
          git push origin processed-project --force
